export const YearStyle = {
  margin: "auto",
  marginTop: "3%",
  width: "90%",
  display: "flex",
  flexWrap: "wrap",
  gap: "20px",
  justifyContent: "flex-start",
  alignItems: "center",
  boxStyle: {
    backgroundImage: "url(/images/classroom.png)",
    backgroundPosition: "center",
    backgroundSize: "contain",
    backgroundRepeat: "no-repeat",
    opacity: "0.8",
    width: "100%",
    borderRadius: "20px",
    height: "170px",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "RGBA(128, 128, 128, 0.7)",
  },
  linkStyle: {
    flex: "0 1 250px",
    textDecoration: "none",
    color: "black",
  },
  headStyle: {
    textAlign: "center",
  },
  stateStyle: {
    textAlign: "center",
    marginTop: "3%",
  },
};
