export const NavbarStyle = {
  navDiv: {
    position: "relative",
    background: "grey",
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: "16px",
    padding: "12px 4%",
  },
  list: {
    display: "flex",
    gap: "22px",
    alignItems: "center",
    listStyle: "none",
    margin: 0,
    padding: 0,
  },
  mobileList: {
    display: "flex",
    flexDirection: "column",
    gap: "14px",
    listStyle: "none",
    margin: 0,
    padding: 0,
  },
  mobileMenu: {
    position: "absolute",
    top: "100%",
    left: 0,
    right: 0,
    background: "white",
    padding: "16px 4%",
    boxShadow: "0 6px 12px rgb(0 0 0 / 0.15)",
    zIndex: 10,
  },
  profImgStyle: {
    width: "40px",
    height: "40px",
    borderRadius: "30px",
    objectFit: "cover",
  },
  profileLink: {
    display: "flex",
    alignItems: "center",
    gap: "10px",
    color: "white",
    textDecoration: "none",
    fontSize: "15px",
  },
  placement: {
    color: "white",
    display: "flex",
    gap: "14px",
    justifyContent: "flex-end",
    alignItems: "center",
  },
  hamburgerSpan: { color: "white" },
  signOut: {
    cursor: "pointer",
    border: "none",
    borderRadius: "8px",
    padding: "8px 14px",
    fontFamily: "inherit",
    fontSize: "14px",
  },
};
