export const SignupStyle = {
    boxShadow: "0 3px 30px rgb(0 0 0 / 0.9)",
    width: "30%",
    borderRadius: "20px",
    margin: "auto",
    marginTop: "2%",
    height: "950px",
    display: "flex",
    flexDirection: "column",
    justifyContent: "center",
    alignItems: "center",
    formStyle: {
      width: "70%",
      display: "flex",
      flexDirection: "column",
      lineHeight: "3rem",
    },
    buttonStyle: {
      cursor: "pointer",
      width: "70%",
      height: "45px",
      fontSize: "18px",
      borderRadius: "10px",
      border: "none",
      marginTop: "40px",
    },
    imageStyle: {
      width: "30px",
      height: "30px",
    },
    spanStyle: {
      display: "flex",
      alignItems: "center",
      background: "white",
      borderRadius: "10px",
      padding: "10px 15px 10px",
      boxShadow: "0 3px 10px rgb(0 0 0 / 0.3)",
    },
    inputStyle: {
      width: "80%",
      padding: "10px 15px 10px",
      fontSize: "18px",
      border: "none",
      outline: "none",
      fontFamily: "inherit",
    },
    iconStyle: {
      height: "10px",
    },
  };